version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: wisdom-server
    working_dir: /app
    ports:
      - "1337:1337"
    command: ["-address=:1337", "-wisdoms=wisdoms.json"]

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: wisdom-client
    working_dir: /app
    depends_on:
      - server
    command: ["-address=server:1337", "-count=5"]
