name: Docker Compose Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker-compose services
        run: docker compose build

      - name: Run docker-compose and wait for exit
        run: |
          set -e
          docker compose up --abort-on-container-exit --exit-code-from client

      - name: Check container exit codes
        run: |
          server_status=$(docker inspect -f '{{.State.ExitCode}}' wisdom-server || echo "999")
          client_status=$(docker inspect -f '{{.State.ExitCode}}' wisdom-client || echo "999")

          echo "Server exited with code: $server_status"
          echo "Client exited with code: $client_status"

          if [ "$server_status" -ne 0 ] || [ "$client_status" -ne 0 ]; then
            echo "❌ One or more containers exited with a non-zero code"
            exit 1
          fi

      - name: Cleanup
        if: always()
        run: docker compose down --volumes --remove-orphans
